# TODO: drop `pip install wjs...` (done elsewhere)
# TODO: use deploy.sh script (ssh ForcedCommand anyway...)

deploy_to_test:
  stage: deploy
  tags:
    - inasset
  image: python:3.9

  variables:
    PIP: "/home/wjs/.virtualenvs/j1-venv/bin/pip"
    UWSGI_VASSAL: "/home/wjs/uwsgi/janeway.ini"

  script:
    - echo "Deploy to test instance"
    - chmod og= $ID_RSA
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "( cd janeway && git checkout jcom && git pull --ff-only https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.sissamedialab.it/wjs/janeway jcom && $PIP install --index-url=$PIP_INDEX_URL -U wjs.jcom_profile && touch --no-dereference $UWSGI_VASSAL )"
  environment:
    name: jcom-test
    url: https://janeway-test.sissamedialab.it/
  rules:
    - if: $CI_COMMIT_BRANCH == "jcom"

services:
  - docker:dind

build_janeway_image:
  stage: build
  tags:
    - dind
  variables:
    TAG: "registry.gitlab.sissamedialab.it/wjs/wjs-profile-project/debian-python-git-janeway"
  script:
    - DOCKER_BUILDKIT=1 docker build --tag $TAG --build-arg CI_JOB_TOKEN --file ./dockerfiles/Dockerfile.wjs ./dockerfiles
    - docker push $TAG
  when: manual



build_prova_image:
  stage: build
  tags:
    - dind
  variables:
    TAG: "registry.gitlab.sissamedialab.it/wjs/wjs-profile-project/prova"
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo -e 'FROM busybox\nRUN echo "hello world"' | docker build --tag $TAG -
    # - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" registry.gitlab.sissamedialab.it
    - docker push $TAG
