# TODO: refactor
# TODO: drop `pip install wjs...` (done elsewhere)
# TODO: what about `manage.py makemigrations --merge`?

deploy_staging:
  stage: deploy
  tags:
    - inasset
  image: python:3.9

  variables:
    PIP: "/home/wjs/.virtualenvs/j1-venv/bin/pip"
    UWSGI_VASSAL: "/home/wjs/uwsgi/janeway.ini"

  script:
    - echo "Deploy to test instance"
    - chmod og= $ID_RSA
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "( cd janeway && git checkout jcom && git pull --ff-only https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.sissamedialab.it/wjs/janeway jcom && $PIP install --index-url=$PIP_INDEX_URL -U wjs.jcom_profile && touch --no-dereference $UWSGI_VASSAL )"
  environment:
    name: jcom-test
    url: https://janeway-test.sissamedialab.it/
  rules:
    - if: $CI_COMMIT_BRANCH == "jcom"

deploy_staging:
  stage: deploy
  tags:
    - inasset
  image: python:3.9

  variables:
    PIP: "/home/wjs/.virtualenvs/j-pp/bin/pip"
    UWSGI_VASSAL: "/home/wjs/uwsgi/janeway-pp.ini"

  script:
    - echo "Deploy to pre-productions instance"
    - chmod og= $ID_RSA
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "( cd janeway-pp && git checkout jcom && git pull --ff-only https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.sissamedialab.it/wjs/janeway jcom && $PIP install --index-url=$PIP_INDEX_URL -U wjs.jcom_profile && touch --no-dereference $UWSGI_VASSAL )"
  environment:
    name: jcom-test
    url: https://janeway-pp.sissamedialab.it/
  when: manual
