# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-27 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywordId', models.CharField(max_length=5)),
                ('keywordName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='KeywordGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupId', models.CharField(max_length=5)),
                ('groupName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='KeywordSubgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subgroupId', models.CharField(max_length=5)),
                ('subgroupName', models.CharField(max_length=200)),
                ('kgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medialab_keywords.KeywordGroup')),
            ],
        ),
        migrations.AddField(
            model_name='keyword',
            name='ksubgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medialab_keywords.KeywordSubgroup'),
        ),
    ]
