# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-24 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actionCod', models.IntegerField()),
                ('actionDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preprintid', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Editor_Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywordId', models.CharField(max_length=5)),
                ('keywordName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='KeywordGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupId', models.CharField(max_length=5)),
                ('groupName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='KeywordSubgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subgroupId', models.CharField(max_length=5)),
                ('subgroupName', models.CharField(max_length=200)),
                ('kgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medialab_keywords.KeywordGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleId', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=200)),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('editorWorkload', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disableFlag', models.IntegerField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medialab_keywords.Role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medialab_keywords.User')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medialab_keywords.Document')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(through='medialab_keywords.User_Role', to='medialab_keywords.Role'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='ksubgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medialab_keywords.KeywordSubgroup'),
        ),
        migrations.AddField(
            model_name='editor_keyword',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medialab_keywords.User'),
        ),
        migrations.AddField(
            model_name='editor_keyword',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medialab_keywords.Keyword'),
        ),
        migrations.AddField(
            model_name='action_history',
            name='agentCod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor', to='medialab_keywords.User'),
        ),
        migrations.AddField(
            model_name='action_history',
            name='realAgentCod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='real_actor', to='medialab_keywords.User'),
        ),
        migrations.AddField(
            model_name='action_history',
            name='userCod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='medialab_keywords.User'),
        ),
        migrations.AddField(
            model_name='action_history',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medialab_keywords.Version'),
        ),
    ]
