# Generated by Django 4.2.22 on 2026-02-25 01:31

import core.model_utils
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "submission",
            "0089_article_abstract_pt_article_title_pt_keyword_word_cy_and_more",
        ),
        ("core", "0111_contacts_name_pt_contacts_role_pt_and_more"),
        ("journal", "0067_issue_cached_display_title_es_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="allowed_sections",
            field=models.ManyToManyField(
                blank=True,
                help_text="Only the selected sections will be available for selection during the submission process",
                to="submission.section",
                verbose_name="Sections available on the issue",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="date_close",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date of submission closing"
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="date_open",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date of submission opening"
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="description",
            field=core.model_utils.JanewayBleachField(
                blank=True,
                default="",
                help_text="Rich text description of the issue for the issue page.",
                verbose_name="Issue presentation",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="description_cy",
            field=core.model_utils.JanewayBleachField(
                blank=True,
                default="",
                help_text="Rich text description of the issue for the issue page.",
                null=True,
                verbose_name="Issue presentation",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="description_de",
            field=core.model_utils.JanewayBleachField(
                blank=True,
                default="",
                help_text="Rich text description of the issue for the issue page.",
                null=True,
                verbose_name="Issue presentation",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="description_en",
            field=core.model_utils.JanewayBleachField(
                blank=True,
                default="",
                help_text="Rich text description of the issue for the issue page.",
                null=True,
                verbose_name="Issue presentation",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="description_en_us",
            field=core.model_utils.JanewayBleachField(
                blank=True,
                default="",
                help_text="Rich text description of the issue for the issue page.",
                null=True,
                verbose_name="Issue presentation",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="description_es",
            field=core.model_utils.JanewayBleachField(
                blank=True,
                default="",
                help_text="Rich text description of the issue for the issue page.",
                null=True,
                verbose_name="Issue presentation",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="description_fr",
            field=core.model_utils.JanewayBleachField(
                blank=True,
                default="",
                help_text="Rich text description of the issue for the issue page.",
                null=True,
                verbose_name="Issue presentation",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="description_nl",
            field=core.model_utils.JanewayBleachField(
                blank=True,
                default="",
                help_text="Rich text description of the issue for the issue page.",
                null=True,
                verbose_name="Issue presentation",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="documents",
            field=models.ManyToManyField(
                blank=True,
                related_name="issue_documents",
                to="core.file",
                verbose_name="Internal documents related to the issue",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="expected_submissions",
            field=models.IntegerField(
                blank=True,
                help_text="Informative field to help editors track progress",
                null=True,
                verbose_name="Expected number of submissions",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="internal_notes",
            field=models.TextField(
                blank=True,
                help_text="Only available in the manager",
                null=True,
                verbose_name="General notes on issue",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="invitees",
            field=models.ManyToManyField(
                blank=True,
                help_text="If any is selected, only the users in this list will be able to select the issue in the submissionprocess",
                related_name="invited_issues",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Invited authors",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="managing_editors",
            field=models.ManyToManyField(
                blank=True,
                related_name="managed_issue",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Editors ",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="short_name",
            field=models.CharField(
                blank=True, default="", help_text="Short name or code", max_length=300
            ),
        ),
        migrations.AddField(
            model_name="journal",
            name="contact_info_pt",
            field=core.model_utils.JanewayBleachField(
                blank=True, null=True, verbose_name="Contact Information"
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Date after which the issue if visible to the public (this does not affect the article's visibility).",
                verbose_name="Publication date",
            ),
        ),
    ]
