# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-15 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_fix_editorial_images_group'),
        ('core', '0074_account_suffix'),
    ]

    operations = [
    ]
