# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-20 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_merge_20220920_0854'),
        ('core', '0076_auto_20220915_1048'),
    ]

    operations = [
    ]
