"""Added for compatibility with Janeway."""

# Generated by Django 4.2.29 on 2026-05-13 14:13

import core.model_utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comms", "0010_historicalnewsitem_body_cy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalnewsitem",
            name="body_pt",
            field=core.model_utils.JanewayBleachField(null=True),
        ),
        migrations.AddField(
            model_name="historicalnewsitem",
            name="custom_byline_pt",
            field=models.CharField(
                blank=True,
                help_text="If you want a custom byline add it here. This will overwrite the display of the user who created the news item with whatever text is added here.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalnewsitem",
            name="title_pt",
            field=core.model_utils.JanewayBleachCharField(null=True),
        ),
    ]
