# Generated by Django 4.2 on 2024-09-27 09:21

from django.db import migrations
from django.template.defaultfilters import linebreaksbr
from django.core.exceptions import ValidationError

from django_bleach.templatetags.bleach_tags import bleach_value

from utils import forms



class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0084_remove_article_jats_article_type_and_more"),
    ]

    operations = [
    ]
