# Generated by Django 4.2.22 on 2026-02-18 10:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0088_auto_20250506_1214"),
    ]

    operations = [
        migrations.AddField(
            model_name="keyword",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="keyword",
            name="deactivated",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="keyword",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="keywordarticle",
            name="weight",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="submissionconfiguration",
            name="autocomplete_keywords",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="submissionconfiguration",
            name="hierarchical_keywords",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="KeywordGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField(default=1)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "parent_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="submission.keywordgroup",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="keyword",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="keywords",
                to="submission.keywordgroup",
            ),
        ),
    ]
